### ISSUE TITLE
Edit / Add User Stories

### ISSUE THREAD

**Issue by stacygriffith** [codeforkansascity/Code-for-KC-Dashboard#8]
1. Create User stories - Stacy
2. Edit / Prioritize - Katherine
3. Evaluate prioritized stories - Josh

**Comment by khambrickKCDigital** [comment]
Need more user stories on the Functional Specifications Worksheet
https://docs.google.com/document/d/1sglyMnJXlxdcz8W3O8kLSHVoLUsqzN4vMunb9B9gAPo/edit

**Comment by khambrickKCDigital** [comment]
Prioritize User Stories created by Stacy https://docs.google.com/document/d/1wHVaW0cElsvHJv-zCOGh4qBtN9qqgCS-bY5QPVdwKkA/edit . Organize by Must Have and Nice To Have
